import { BACKEND_URL, MAPBOX_ACCESS_TOKEN, MAPBOX_STYLE } from "@env";

export const CONFIG_APP = {
  BACKEND_URL: BACKEND_URL || "",
  MAPBOX_ACCESS_TOKEN: MAPBOX_ACCESS_TOKEN || "",
  MAPBOX_STYLE: MAPBOX_STYLE || "",
  ACCESS_TOKEN_COOKIE: "ACCESS_TOKEN_SHOP_MOBILE",
  REFRESH_TOKEN_COOKIE: "REFRESH_TOKEN_SHOP_MOBILE",
  TOKENS_STORAGE_NAME: "SHOP_TOKENS_STORAGE",
  DEFAULT_MAP_CENTER_LNG: 37.80358599891716,
  DEFAULT_MAP_CENTER_LAT: 48.013597598505555,
} as const;
